# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "vector_geometry"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Andrew Berkeley"]
  s.date = "2013-05-31"
  s.description = "Cartesian and spherical geometry using vectors"
  s.email = "andrew.berkeley.is@googlemail.com"
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "COPYING",
    "Gemfile",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/geometry/geometry.rb",
    "lib/geometry/spheroid/base.rb",
    "lib/geometry/spheroid/sphere.rb",
    "lib/geometry/vector/earth_vector.rb",
    "lib/geometry/vector/geo_vector.rb",
    "lib/geometry/vector/vector.rb",
    "lib/vector_geometry.rb",
    "spec/exercises_spec.rb",
    "spec/geo_vector_spec.rb",
    "spec/spec_helper.rb",
    "spec/vector_spec.rb",
    "vector-geometry.gemspec"
  ]
  s.homepage = "https://github.com/spatchcock/vector_geometry"
  s.licenses = ["GNU Affero General Public License"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Cartesian and spherical geometry using vectors"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<rspec>, ["~> 2.6.0"])
      s.add_development_dependency(%q<rdoc>, [">= 0"])
    else
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<rspec>, ["~> 2.6.0"])
      s.add_dependency(%q<rdoc>, [">= 0"])
    end
  else
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<rspec>, ["~> 2.6.0"])
    s.add_dependency(%q<rdoc>, [">= 0"])
  end
end

